"""``agenticapi init`` — project scaffolding command.

Generates a ready-to-run AgenticAPI project directory with a handler,
tools, eval set, and configuration. Works with ``MockBackend`` out of
the box; switches to a real LLM provider when an API key env var is set.
"""

from __future__ import annotations

from pathlib import Path
from string import Template

# ---------------------------------------------------------------------------
# Templates (plain Python string.Template — no Jinja2 dependency)
# ---------------------------------------------------------------------------

_APP_PY = '''\
"""AgenticAPI application generated by ``agenticapi init``."""

from __future__ import annotations

import os
from typing import TYPE_CHECKING

from agenticapi import AgenticApp, AgentResponse, HarnessEngine, tool
from agenticapi.harness.policy import CodePolicy
from agenticapi.runtime.llm import MockBackend
from agenticapi.runtime.tools import ToolRegistry

if TYPE_CHECKING:
    from agenticapi.interface.intent import Intent
    from agenticapi.runtime.context import AgentContext

# ── LLM backend ──────────────────────────────────────────────────────
# Set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GOOGLE_API_KEY to use a
# real provider. Otherwise MockBackend is used for local development.

_backend_name = "MockBackend"

if os.environ.get("ANTHROPIC_API_KEY"):
    from agenticapi.runtime.llm import AnthropicBackend

    llm = AnthropicBackend()
    _backend_name = "AnthropicBackend"
elif os.environ.get("OPENAI_API_KEY"):
    from agenticapi.runtime.llm import OpenAIBackend

    llm = OpenAIBackend()
    _backend_name = "OpenAIBackend"
elif os.environ.get("GOOGLE_API_KEY"):
    from agenticapi.runtime.llm import GeminiBackend

    llm = GeminiBackend()
    _backend_name = "GeminiBackend"
else:
    llm = MockBackend(responses=["Here is the answer to your question."])

_suffix = " (set an LLM API key for real provider)" if _backend_name == "MockBackend" else ""
print(f"Running with {_backend_name}" + _suffix)

# ── Tools ────────────────────────────────────────────────────────────
from tools import greet_user, calculate  # noqa: E402

registry = ToolRegistry()
registry.register(greet_user)
registry.register(calculate)

# ── Harness ──────────────────────────────────────────────────────────
harness = HarnessEngine(
    policies=[
        CodePolicy(
            forbidden_imports=["os", "subprocess", "shutil"],
            forbidden_builtins=["eval", "exec", "compile"],
        ),
    ],
)

# ── App ──────────────────────────────────────────────────────────────
app = AgenticApp(
    title="$project_name",
    llm=llm,
    harness=harness,
    tools=registry,
)


@app.agent_endpoint(name="ask")
async def ask(intent: Intent, context: AgentContext) -> AgentResponse:
    """Answer a question using the agent pipeline."""
    return AgentResponse(
        result={"answer": f"Processed: {intent.raw}"},
        reasoning="Direct handler response",
    )
'''

_TOOLS_PY = '''\
"""Tool definitions for the $project_name project."""

from __future__ import annotations

from agenticapi import tool


@tool(description="Greet a user by name")
async def greet_user(name: str) -> str:
    """Return a personalised greeting."""
    return f"Hello, {name}! Welcome to $project_name."


@tool(description="Perform basic arithmetic")
async def calculate(expression: str) -> str:
    """Evaluate a simple arithmetic expression safely."""
    allowed = set("0123456789+-*/(). ")
    if not all(c in allowed for c in expression):
        return "Error: only basic arithmetic is supported"
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return str(result)
    except Exception:
        return "Error: invalid expression"
'''

_GOLDEN_YAML = """\
# Eval set for $project_name — works with MockBackend.
name: golden
description: Smoke tests for the ask endpoint
cases:
  - intent: "hello world"
    endpoint: ask
    expect_status: 200

  - intent: "what is 2+2?"
    endpoint: ask
    expect_status: 200

  - intent: "greet Alice"
    endpoint: ask
    expect_status: 200
"""

_ENV_EXAMPLE = """\
# Uncomment one of these to use a real LLM provider:
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
# GOOGLE_API_KEY=AI...
"""

_PYPROJECT_TOML = """\
[project]
name = "$project_name"
version = "0.1.0"
description = "An AgenticAPI project"
requires-python = ">=3.13"
dependencies = [
    "agenticapi>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
"""

_README_MD = """\
# $project_name

An [AgenticAPI](https://github.com/anthropics/agenticapi) project.

## Quick start

```bash
# 1. Install dependencies
pip install agenticapi

# 2. Run the development server
agenticapi dev --app app:app

# 3. Test with curl
curl -X POST http://localhost:8000/agent/ask \\
  -H "Content-Type: application/json" \\
  -d '{"intent": "hello world"}'
```

## Using a real LLM

Set one of these environment variables:

```bash
export ANTHROPIC_API_KEY=sk-ant-...   # Claude
export OPENAI_API_KEY=sk-...          # GPT
export GOOGLE_API_KEY=AI...           # Gemini
```

## Running evals

```bash
agenticapi eval --set evals/golden.yaml --app app:app
```
"""


def run_init(project_name: str, template: str = "default") -> Path:
    """Generate a new AgenticAPI project directory.

    Args:
        project_name: Name of the project (used as directory name).
        template: Template variant (``"default"``, ``"chat"``,
            ``"tool-calling"``). Only ``"default"`` is shipped in
            this version.

    Returns:
        The path to the generated project directory.

    Raises:
        SystemExit: If the target directory already exists.
    """
    project_dir = Path.cwd() / project_name
    if project_dir.exists():
        print(f"Error: directory '{project_name}' already exists.")
        raise SystemExit(1)

    project_dir.mkdir(parents=True)
    evals_dir = project_dir / "evals"
    evals_dir.mkdir()

    ctx = {"project_name": project_name}

    (project_dir / "app.py").write_text(Template(_APP_PY).safe_substitute(ctx))
    (project_dir / "tools.py").write_text(Template(_TOOLS_PY).safe_substitute(ctx))
    (evals_dir / "golden.yaml").write_text(Template(_GOLDEN_YAML).safe_substitute(ctx))
    (project_dir / ".env.example").write_text(_ENV_EXAMPLE)
    (project_dir / "pyproject.toml").write_text(Template(_PYPROJECT_TOML).safe_substitute(ctx))
    (project_dir / "README.md").write_text(Template(_README_MD).safe_substitute(ctx))

    print(f"Created project '{project_name}' at {project_dir}")
    print(f"Run `cd {project_name} && agenticapi dev --app app:app` to start.")

    return project_dir
