"""Execution trace for audit recording.

Captures the full lifecycle of an agent operation including intent,
generated code, policy evaluations, execution result, and timing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datetime import datetime


@dataclass(slots=True)
class ExecutionTrace:
    """Complete trace of an agent execution for auditing.

    Captures all stages of the execution pipeline: intent parsing,
    code generation, policy evaluation, sandbox execution, and the
    final result.

    Attributes:
        trace_id: Unique identifier for this execution trace.
        endpoint_name: Name of the agent endpoint that handled the request.
        timestamp: When the execution started.
        intent_raw: The original natural language request.
        intent_action: The classified action type (read, write, etc.).
        generated_code: The Python code generated by the LLM.
        reasoning: Optional chain-of-thought reasoning from the LLM.
        policy_evaluations: Results from each policy evaluation.
        execution_result: The output of the sandbox execution.
        execution_duration_ms: Total execution duration in milliseconds.
        error: Error message if the execution failed.
        llm_usage: Token usage statistics from LLM calls.
        approval_request_id: ID of an associated approval request, if any.
        stream_events: Phase F8 — list of typed agent lifecycle events
            emitted on this request's :class:`AgentStream`. Empty for
            non-streaming endpoints. Each entry is the
            ``model_dump()`` of an
            :class:`agenticapi.interface.stream.AgentEvent` so it
            JSON-serialises cleanly into the audit store.
    """

    trace_id: str
    endpoint_name: str
    timestamp: datetime
    intent_raw: str
    intent_action: str = ""
    generated_code: str = ""
    reasoning: str | None = None
    policy_evaluations: list[dict[str, Any]] = field(default_factory=list)
    execution_result: Any = None
    execution_duration_ms: float = 0.0
    error: str | None = None
    llm_usage: dict[str, int] | None = None
    approval_request_id: str | None = None
    stream_events: list[dict[str, Any]] = field(default_factory=list)
